name: Sync(手动执行同步最新部署)
on:
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/bullfly666/percollect.git"
          source_branch: "scf2"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}
